# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: infoshare.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import timestamp_pb2 as google_dot_protobuf_dot_timestamp__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='infoshare.proto',
  package='CitbrainsMessage',
  syntax='proto2',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0finfoshare.proto\x12\x10\x43itbrainsMessage\x1a\x1fgoogle/protobuf/timestamp.proto\"8\n\x05Pos2D\x12\r\n\x05pos_x\x18\x01 \x02(\x11\x12\r\n\x05pos_y\x18\x02 \x02(\x11\x12\x11\n\tpos_theta\x18\x03 \x02(\x11\"[\n\x07Pos2DCf\x12)\n\x08position\x18\x01 \x02(\x0b\x32\x17.CitbrainsMessage.Pos2D\x12\x12\n\nconfidence\x18\x02 \x02(\x0c\x12\x11\n\tis_detect\x18\x03 \x01(\x08\"\xa5\x04\n\x0bSharingData\x12\n\n\x02id\x18\x01 \x02(\x0c\x12\x12\n\nteam_color\x18\x13 \x02(\x0c\x12\x0e\n\x06status\x18\x04 \x01(\x0c\x12\x0b\n\x03\x66ps\x18\x05 \x01(\x0c\x12\x0f\n\x07voltage\x18\x06 \x01(\x0c\x12\x13\n\x0btemperature\x18\x07 \x01(\x0c\x12\x15\n\rhighest_servo\x18\x08 \x01(\x0c\x12\x0f\n\x07\x63ommand\x18\t \x01(\x0c\x12\x1d\n\x15\x63urrent_behavior_name\x18\n \x01(\x0c\x12-\n\x0cour_robot_gl\x18\x0c \x03(\x0b\x32\x17.CitbrainsMessage.Pos2D\x12/\n\x0e\x65nemy_robot_gl\x18\r \x03(\x0b\x32\x17.CitbrainsMessage.Pos2D\x12.\n\rblack_pole_gl\x18\x0e \x03(\x0b\x32\x17.CitbrainsMessage.Pos2D\x12/\n\x0etarget_pos_vec\x18\x0f \x03(\x0b\x32\x17.CitbrainsMessage.Pos2D\x12-\n\nball_gl_cf\x18\x10 \x01(\x0b\x32\x19.CitbrainsMessage.Pos2DCf\x12.\n\x0bself_pos_cf\x18\x11 \x01(\x0b\x32\x19.CitbrainsMessage.Pos2DCf\x12-\n\ttimestamp\x18\x14 \x01(\x0b\x32\x1a.google.protobuf.Timestamp\"\x1d\n\tTeamColor\x12\x10\n\x0c\x43OLOR_OFFSET\x10\x01'
  ,
  dependencies=[google_dot_protobuf_dot_timestamp__pb2.DESCRIPTOR,])



_SHARINGDATA_TEAMCOLOR = _descriptor.EnumDescriptor(
  name='TeamColor',
  full_name='CitbrainsMessage.SharingData.TeamColor',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='COLOR_OFFSET', index=0, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=742,
  serialized_end=771,
)
_sym_db.RegisterEnumDescriptor(_SHARINGDATA_TEAMCOLOR)


_POS2D = _descriptor.Descriptor(
  name='Pos2D',
  full_name='CitbrainsMessage.Pos2D',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='pos_x', full_name='CitbrainsMessage.Pos2D.pos_x', index=0,
      number=1, type=17, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pos_y', full_name='CitbrainsMessage.Pos2D.pos_y', index=1,
      number=2, type=17, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='pos_theta', full_name='CitbrainsMessage.Pos2D.pos_theta', index=2,
      number=3, type=17, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=70,
  serialized_end=126,
)


_POS2DCF = _descriptor.Descriptor(
  name='Pos2DCf',
  full_name='CitbrainsMessage.Pos2DCf',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='position', full_name='CitbrainsMessage.Pos2DCf.position', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='confidence', full_name='CitbrainsMessage.Pos2DCf.confidence', index=1,
      number=2, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='is_detect', full_name='CitbrainsMessage.Pos2DCf.is_detect', index=2,
      number=3, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=128,
  serialized_end=219,
)


_SHARINGDATA = _descriptor.Descriptor(
  name='SharingData',
  full_name='CitbrainsMessage.SharingData',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='CitbrainsMessage.SharingData.id', index=0,
      number=1, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='team_color', full_name='CitbrainsMessage.SharingData.team_color', index=1,
      number=19, type=12, cpp_type=9, label=2,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='status', full_name='CitbrainsMessage.SharingData.status', index=2,
      number=4, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='fps', full_name='CitbrainsMessage.SharingData.fps', index=3,
      number=5, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='voltage', full_name='CitbrainsMessage.SharingData.voltage', index=4,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='temperature', full_name='CitbrainsMessage.SharingData.temperature', index=5,
      number=7, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='highest_servo', full_name='CitbrainsMessage.SharingData.highest_servo', index=6,
      number=8, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='command', full_name='CitbrainsMessage.SharingData.command', index=7,
      number=9, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='current_behavior_name', full_name='CitbrainsMessage.SharingData.current_behavior_name', index=8,
      number=10, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=b"",
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='our_robot_gl', full_name='CitbrainsMessage.SharingData.our_robot_gl', index=9,
      number=12, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='enemy_robot_gl', full_name='CitbrainsMessage.SharingData.enemy_robot_gl', index=10,
      number=13, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='black_pole_gl', full_name='CitbrainsMessage.SharingData.black_pole_gl', index=11,
      number=14, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='target_pos_vec', full_name='CitbrainsMessage.SharingData.target_pos_vec', index=12,
      number=15, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='ball_gl_cf', full_name='CitbrainsMessage.SharingData.ball_gl_cf', index=13,
      number=16, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='self_pos_cf', full_name='CitbrainsMessage.SharingData.self_pos_cf', index=14,
      number=17, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='timestamp', full_name='CitbrainsMessage.SharingData.timestamp', index=15,
      number=20, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _SHARINGDATA_TEAMCOLOR,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=222,
  serialized_end=771,
)

_POS2DCF.fields_by_name['position'].message_type = _POS2D
_SHARINGDATA.fields_by_name['our_robot_gl'].message_type = _POS2D
_SHARINGDATA.fields_by_name['enemy_robot_gl'].message_type = _POS2D
_SHARINGDATA.fields_by_name['black_pole_gl'].message_type = _POS2D
_SHARINGDATA.fields_by_name['target_pos_vec'].message_type = _POS2D
_SHARINGDATA.fields_by_name['ball_gl_cf'].message_type = _POS2DCF
_SHARINGDATA.fields_by_name['self_pos_cf'].message_type = _POS2DCF
_SHARINGDATA.fields_by_name['timestamp'].message_type = google_dot_protobuf_dot_timestamp__pb2._TIMESTAMP
_SHARINGDATA_TEAMCOLOR.containing_type = _SHARINGDATA
DESCRIPTOR.message_types_by_name['Pos2D'] = _POS2D
DESCRIPTOR.message_types_by_name['Pos2DCf'] = _POS2DCF
DESCRIPTOR.message_types_by_name['SharingData'] = _SHARINGDATA
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Pos2D = _reflection.GeneratedProtocolMessageType('Pos2D', (_message.Message,), {
  'DESCRIPTOR' : _POS2D,
  '__module__' : 'infoshare_pb2'
  # @@protoc_insertion_point(class_scope:CitbrainsMessage.Pos2D)
  })
_sym_db.RegisterMessage(Pos2D)

Pos2DCf = _reflection.GeneratedProtocolMessageType('Pos2DCf', (_message.Message,), {
  'DESCRIPTOR' : _POS2DCF,
  '__module__' : 'infoshare_pb2'
  # @@protoc_insertion_point(class_scope:CitbrainsMessage.Pos2DCf)
  })
_sym_db.RegisterMessage(Pos2DCf)

SharingData = _reflection.GeneratedProtocolMessageType('SharingData', (_message.Message,), {
  'DESCRIPTOR' : _SHARINGDATA,
  '__module__' : 'infoshare_pb2'
  # @@protoc_insertion_point(class_scope:CitbrainsMessage.SharingData)
  })
_sym_db.RegisterMessage(SharingData)


# @@protoc_insertion_point(module_scope)
